/* Gnam curated recipe bank.
   Quantities are per 2 servings. Nutrition is an indicative estimate per serving,
   intended for planning rather than clinical dietary use. */
const RECIPES = [
{id:'pasta-zucchine',name:'Pasta integrale, zucchine e ricotta',time:20,diff:1,tags:['mediterranea','vegetariana','fibra'],style:['normal','elegant'],ingredients:[['pasta integrale',160,'g'],['zucchine',300,'g'],['ricotta',160,'g'],['cipolla',60,'g'],['olio evo',15,'g']],kcal:520,p:24,c:67,f:17,veg:2,grain:1,protein:'dairy'},
{id:'pollo-peperoni',name:'Pollo al limone con peperoni e riso',time:30,diff:2,tags:['alta-proteina','mediterranea'],style:['normal','sport','elegant'],ingredients:[['petto di pollo',320,'g'],['peperoni',250,'g'],['riso',150,'g'],['limone',1,'pz'],['olio evo',15,'g']],kcal:610,p:45,c:66,f:18,veg:2,grain:1,protein:'chicken'},
{id:'lenticchie-pomodoro',name:'Lenticchie al pomodoro con pane integrale',time:25,diff:1,tags:['legumi','economica','fibra'],style:['normal','sport'],ingredients:[['lenticchie cotte',360,'g'],['passata di pomodoro',250,'g'],['carote',120,'g'],['cipolla',60,'g'],['pane integrale',120,'g'],['olio evo',15,'g']],kcal:545,p:27,c:81,f:13,veg:2,grain:1,protein:'legume'},
{id:'salmone-broccoli',name:'Salmone, broccoli e patate al forno',time:35,diff:2,tags:['omega-3','forno','semplice'],style:['normal','sport','elegant'],ingredients:[['salmone',280,'g'],['broccoli',300,'g'],['patate',420,'g'],['olio evo',15,'g']],kcal:625,p:39,c:52,f:27,veg:2,grain:0,protein:'fish'},
{id:'frittata-spinaci',name:'Frittata al forno con spinaci e pane',time:20,diff:1,tags:['uova','vegetariana','veloce'],style:['normal','sport','elegant'],ingredients:[['uova',4,'pz'],['spinaci',250,'g'],['parmigiano',30,'g'],['pane integrale',120,'g'],['olio evo',10,'g']],kcal:500,p:29,c:43,f:22,veg:1,grain:1,protein:'egg'},
{id:'ceci-couscous',name:'Cous cous con ceci, zucchine e feta',time:20,diff:1,tags:['legumi','mediterranea','vegetariana'],style:['normal','elegant','sport'],ingredients:[['cous cous',150,'g'],['ceci cotti',320,'g'],['zucchine',250,'g'],['pomodori',180,'g'],['feta',80,'g'],['olio evo',15,'g']],kcal:575,p:25,c:82,f:16,veg:2,grain:1,protein:'legume'},
{id:'tonno-fagioli',name:'Insalata tiepida di tonno, fagioli e pomodoro',time:15,diff:1,tags:['zero sbatti','legumi','proteina'],style:['normal','sport'],ingredients:[['tonno al naturale',240,'g'],['fagioli cannellini',300,'g'],['pomodori',220,'g'],['cipolla rossa',50,'g'],['pane integrale',100,'g'],['olio evo',15,'g']],kcal:520,p:41,c:51,f:15,veg:2,grain:1,protein:'fish'},
{id:'pasta-lenticchie',name:'Pasta e lenticchie cremosa',time:30,diff:2,tags:['comfort','legumi','fibra'],style:['normal','sport'],ingredients:[['pasta',160,'g'],['lenticchie cotte',300,'g'],['passata di pomodoro',200,'g'],['carote',80,'g'],['cipolla',50,'g'],['olio evo',15,'g']],kcal:560,p:27,c:91,f:12,veg:1,grain:1,protein:'legume'},
{id:'riso-verdure-tofu',name:'Riso saltato con tofu e verdure',time:25,diff:2,tags:['plant-based','colorato','proteina'],style:['normal','sport'],ingredients:[['riso',150,'g'],['tofu',240,'g'],['broccoli',180,'g'],['carote',120,'g'],['peperoni',150,'g'],['olio evo',15,'g']],kcal:570,p:28,c:72,f:18,veg:3,grain:1,protein:'tofu'},
{id:'pasta-tonno',name:'Pasta al tonno, pomodoro e olive',time:20,diff:1,tags:['veloce','dispensa','mediterranea'],style:['normal'],ingredients:[['pasta',160,'g'],['tonno al naturale',200,'g'],['passata di pomodoro',220,'g'],['olive',40,'g'],['olio evo',10,'g']],kcal:535,p:33,c:73,f:14,veg:1,grain:1,protein:'fish'},
{id:'pollo-curry-yogurt',name:'Pollo al curry delicato con yogurt e riso',time:30,diff:2,tags:['speziato','alta-proteina'],style:['sport','normal'],ingredients:[['petto di pollo',320,'g'],['yogurt greco',160,'g'],['riso',150,'g'],['carote',120,'g'],['spinaci',120,'g'],['olio evo',15,'g']],kcal:600,p:50,c:64,f:15,veg:2,grain:1,protein:'chicken'},
{id:'merluzzo-patate',name:'Merluzzo mediterraneo con patate e pomodori',time:30,diff:2,tags:['pesce','leggero','forno'],style:['normal','elegant'],ingredients:[['merluzzo',320,'g'],['patate',420,'g'],['pomodori',220,'g'],['olive',35,'g'],['olio evo',15,'g']],kcal:520,p:40,c:54,f:17,veg:2,grain:0,protein:'fish'},
{id:'orzo-feta',name:'Orzo perlato con verdure arrosto e feta',time:35,diff:2,tags:['mediterranea','vegetariana','meal prep'],style:['normal','elegant'],ingredients:[['orzo',160,'g'],['zucchine',180,'g'],['peperoni',180,'g'],['melanzane',180,'g'],['feta',80,'g'],['olio evo',15,'g']],kcal:565,p:21,c:75,f:20,veg:3,grain:1,protein:'dairy'},
{id:'shakshuka',name:'Shakshuka rapida con pane integrale',time:25,diff:2,tags:['uova','pomodoro','brunch-for-dinner'],style:['normal','elegant'],ingredients:[['uova',4,'pz'],['passata di pomodoro',300,'g'],['peperoni',180,'g'],['cipolla',70,'g'],['pane integrale',120,'g'],['olio evo',15,'g']],kcal:510,p:28,c:54,f:20,veg:2,grain:1,protein:'egg'},
{id:'gnocchi-pomodoro',name:'Gnocchi al pomodoro e mozzarella',time:20,diff:1,tags:['comfort','veloce','italiana'],style:['normal','elegant'],ingredients:[['gnocchi',400,'g'],['passata di pomodoro',250,'g'],['mozzarella',150,'g'],['spinaci',120,'g'],['olio evo',10,'g']],kcal:590,p:25,c:83,f:19,veg:1,grain:0,protein:'dairy'},
{id:'pasta-broccoli-ricotta',name:'Pasta cremosa broccoli e ricotta',time:25,diff:1,tags:['vegetariana','fibra','cremosa'],style:['normal','sport'],ingredients:[['pasta integrale',160,'g'],['broccoli',300,'g'],['ricotta',160,'g'],['parmigiano',20,'g'],['olio evo',15,'g']],kcal:545,p:26,c:72,f:17,veg:2,grain:1,protein:'dairy'},
{id:'uova-patate-spinaci',name:'Uova al tegamino con patate e spinaci',time:25,diff:1,tags:['uova','semplice','budget'],style:['normal'],ingredients:[['uova',4,'pz'],['patate',400,'g'],['spinaci',220,'g'],['pane integrale',80,'g'],['olio evo',15,'g']],kcal:555,p:27,c:57,f:23,veg:2,grain:1,protein:'egg'},
{id:'pollo-zucchine',name:'Straccetti di pollo con zucchine e cous cous',time:25,diff:1,tags:['alta-proteina','veloce'],style:['normal','sport'],ingredients:[['petto di pollo',320,'g'],['zucchine',300,'g'],['cous cous',150,'g'],['olio evo',15,'g']],kcal:565,p:45,c:60,f:16,veg:2,grain:1,protein:'chicken'},
{id:'salmon-pasta',name:'Pasta cremosa al salmone e spinaci',time:25,diff:2,tags:['pesce','elegante','omega-3'],style:['elegant','normal'],ingredients:[['pasta',160,'g'],['salmone',220,'g'],['spinaci',180,'g'],['yogurt greco',120,'g'],['olio evo',10,'g']],kcal:625,p:38,c:68,f:23,veg:1,grain:1,protein:'fish'},
{id:'insalata-pollo',name:'Insalata croccante di pollo, ceci e verdure',time:20,diff:1,tags:['fresh','alta-proteina','fibre'],style:['normal','sport'],ingredients:[['petto di pollo',280,'g'],['ceci cotti',220,'g'],['lattuga',180,'g'],['pomodori',180,'g'],['carote',100,'g'],['olio evo',15,'g']],kcal:500,p:46,c:44,f:15,veg:3,grain:0,protein:'chicken'},
{id:'riso-pollo-verdure',name:'Bowl di riso, pollo e verdure',time:30,diff:2,tags:['meal prep','sport','completo'],style:['sport','normal'],ingredients:[['riso',160,'g'],['petto di pollo',280,'g'],['broccoli',150,'g'],['carote',100,'g'],['peperoni',120,'g'],['olio evo',15,'g']],kcal:605,p:45,c:73,f:15,veg:3,grain:1,protein:'chicken'},
{id:'pasta-ceci-pomodoro',name:'Pasta con ceci, rosmarino e pomodoro',time:25,diff:1,tags:['legumi','italiana','fibra'],style:['normal','sport'],ingredients:[['pasta',150,'g'],['ceci cotti',300,'g'],['passata di pomodoro',250,'g'],['cipolla',60,'g'],['olio evo',15,'g']],kcal:575,p:25,c:91,f:13,veg:1,grain:1,protein:'legume'},
{id:'feta-verdure-pita',name:'Pita mediterranea con feta e verdure',time:15,diff:1,tags:['vegetariana','veloce','colorata'],style:['normal'],ingredients:[['pane pita',160,'g'],['feta',100,'g'],['pomodori',180,'g'],['cetrioli',160,'g'],['peperoni',120,'g'],['yogurt greco',100,'g'],['olio evo',10,'g']],kcal:525,p:23,c:66,f:18,veg:3,grain:1,protein:'dairy'},
{id:'merluzzo-ceci',name:'Merluzzo in padella con ceci e spinaci',time:25,diff:2,tags:['pesce','legumi','ferro'],style:['normal','sport'],ingredients:[['merluzzo',320,'g'],['ceci cotti',260,'g'],['spinaci',200,'g'],['pomodori',150,'g'],['olio evo',15,'g']],kcal:510,p:47,c:48,f:14,veg:2,grain:0,protein:'fish'},
{id:'pollo-melanzane',name:'Pollo con melanzane al pomodoro',time:30,diff:2,tags:['mediterranea','forno'],style:['normal','elegant'],ingredients:[['petto di pollo',320,'g'],['melanzane',300,'g'],['passata di pomodoro',220,'g'],['riso',120,'g'],['olio evo',15,'g']],kcal:565,p:44,c:58,f:16,veg:2,grain:1,protein:'chicken'},
{id:'pasta-melanzane-mozzarella',name:'Pasta melanzane, pomodoro e mozzarella',time:30,diff:2,tags:['italiana','comfort','vegetariana'],style:['normal','elegant'],ingredients:[['pasta',160,'g'],['melanzane',260,'g'],['passata di pomodoro',250,'g'],['mozzarella',120,'g'],['olio evo',15,'g']],kcal:610,p:27,c:82,f:20,veg:2,grain:1,protein:'dairy'},
{id:'frittata-zucchine',name:'Frittata di zucchine e ricotta con insalata',time:20,diff:1,tags:['uova','light','vegetariana'],style:['normal','elegant'],ingredients:[['uova',4,'pz'],['zucchine',300,'g'],['ricotta',100,'g'],['lattuga',180,'g'],['pane integrale',100,'g'],['olio evo',10,'g']],kcal:500,p:30,c:44,f:22,veg:2,grain:1,protein:'egg'},
{id:'riso-lenticchie',name:'Bowl di riso, lenticchie e verdure',time:30,diff:2,tags:['plant-forward','fibra','meal prep'],style:['normal','sport'],ingredients:[['riso',140,'g'],['lenticchie cotte',300,'g'],['carote',120,'g'],['broccoli',180,'g'],['olio evo',15,'g']],kcal:560,p:24,c:89,f:12,veg:2,grain:1,protein:'legume'},
{id:'tacchino-patate',name:'Tacchino alle erbe con patate e carote',time:35,diff:2,tags:['alta-proteina','forno','facile'],style:['sport','normal','elegant'],ingredients:[['fesa di tacchino',320,'g'],['patate',400,'g'],['carote',180,'g'],['olio evo',15,'g']],kcal:555,p:47,c:53,f:16,veg:2,grain:0,protein:'turkey'},
{id:'orata-patate',name:'Orata al forno con patate e pomodorini',time:35,diff:2,tags:['pesce','elegante','mediterranea'],style:['elegant','normal'],ingredients:[['orata',360,'g'],['patate',400,'g'],['pomodori',220,'g'],['olio evo',15,'g']],kcal:600,p:43,c:50,f:23,veg:2,grain:0,protein:'fish'},
{id:'risotto-funghi',name:'Risotto ai funghi e parmigiano',time:35,diff:2,tags:['elegante','vegetariana','italiana'],style:['elegant','normal'],ingredients:[['riso',170,'g'],['funghi',300,'g'],['parmigiano',45,'g'],['cipolla',50,'g'],['olio evo',15,'g']],kcal:565,p:20,c:79,f:18,veg:1,grain:1,protein:'dairy'},
{id:'pasta-piselli',name:'Pasta con piselli, ricotta e limone',time:20,diff:1,tags:['veloce','vegetariana','fresh'],style:['normal','elegant'],ingredients:[['pasta',160,'g'],['piselli',260,'g'],['ricotta',140,'g'],['limone',1,'pz'],['olio evo',15,'g']],kcal:550,p:25,c:81,f:15,veg:1,grain:1,protein:'dairy'},
{id:'ceci-spinaci-pane',name:'Ceci cremosi agli spinaci con pane tostato',time:20,diff:1,tags:['legumi','plant-forward','comfort'],style:['normal','sport'],ingredients:[['ceci cotti',340,'g'],['spinaci',250,'g'],['passata di pomodoro',180,'g'],['pane integrale',120,'g'],['olio evo',15,'g']],kcal:540,p:24,c:77,f:15,veg:2,grain:1,protein:'legume'},
{id:'tuna-pasta-lemon',name:'Pasta fredda tonno, pomodoro e limone',time:15,diff:1,tags:['zero forno','estate','veloce'],style:['normal'],ingredients:[['pasta',160,'g'],['tonno al naturale',220,'g'],['pomodori',220,'g'],['limone',1,'pz'],['olio evo',15,'g']],kcal:525,p:36,c:72,f:13,veg:1,grain:1,protein:'fish'},
{id:'pollo-yogurt-cetriolo',name:'Piadina integrale pollo, yogurt e verdure',time:15,diff:1,tags:['veloce','fresh','alta-proteina'],style:['normal','sport'],ingredients:[['piadina integrale',160,'g'],['petto di pollo',240,'g'],['yogurt greco',100,'g'],['cetrioli',120,'g'],['pomodori',150,'g'],['lattuga',100,'g']],kcal:540,p:43,c:55,f:17,veg:3,grain:1,protein:'chicken'},
{id:'tofu-curry',name:'Tofu al curry con broccoli e riso',time:30,diff:2,tags:['plant-based','speziato','sport'],style:['sport','normal'],ingredients:[['tofu',280,'g'],['riso',150,'g'],['broccoli',250,'g'],['carote',120,'g'],['yogurt greco',80,'g'],['olio evo',15,'g']],kcal:600,p:30,c:71,f:22,veg:2,grain:1,protein:'tofu'},
{id:'uova-piselli',name:'Uova strapazzate, piselli e pane croccante',time:15,diff:1,tags:['uova','veloce','budget'],style:['normal'],ingredients:[['uova',4,'pz'],['piselli',240,'g'],['pane integrale',120,'g'],['pomodori',150,'g'],['olio evo',10,'g']],kcal:505,p:28,c:57,f:19,veg:2,grain:1,protein:'egg'},
{id:'insalata-salmone',name:'Insalata di salmone, patate e fagiolini',time:25,diff:1,tags:['omega-3','fresh','completa'],style:['elegant','normal','sport'],ingredients:[['salmone',260,'g'],['patate',350,'g'],['fagiolini',240,'g'],['pomodori',150,'g'],['olio evo',15,'g']],kcal:560,p:36,c:47,f:24,veg:2,grain:0,protein:'fish'},
{id:'pasta-tacchino-spinaci',name:'Pasta con tacchino, spinaci e pomodoro',time:25,diff:1,tags:['alta-proteina','veloce'],style:['sport','normal'],ingredients:[['pasta integrale',160,'g'],['fesa di tacchino',260,'g'],['spinaci',180,'g'],['passata di pomodoro',220,'g'],['olio evo',15,'g']],kcal:590,p:47,c:70,f:15,veg:2,grain:1,protein:'turkey'},
{id:'couscous-pollo',name:'Cous cous mediterraneo con pollo e verdure',time:25,diff:1,tags:['meal prep','colorato','alta-proteina'],style:['sport','normal'],ingredients:[['cous cous',150,'g'],['petto di pollo',280,'g'],['zucchine',150,'g'],['peperoni',150,'g'],['pomodori',150,'g'],['olio evo',15,'g']],kcal:565,p:45,c:64,f:15,veg:3,grain:1,protein:'chicken'},
{id:'melanzane-ceci',name:'Melanzane ripiene di ceci e pomodoro',time:40,diff:2,tags:['vegetariana','forno','legumi'],style:['normal','elegant'],ingredients:[['melanzane',380,'g'],['ceci cotti',280,'g'],['passata di pomodoro',220,'g'],['mozzarella',80,'g'],['olio evo',15,'g']],kcal:520,p:26,c:58,f:21,veg:2,grain:0,protein:'legume'},
{id:'patate-tonno',name:'Patate schiacciate con tonno, yogurt e insalata',time:25,diff:1,tags:['zero sbatti','fresh','alta-proteina'],style:['normal','sport'],ingredients:[['patate',450,'g'],['tonno al naturale',220,'g'],['yogurt greco',120,'g'],['lattuga',180,'g'],['pomodori',150,'g'],['olio evo',15,'g']],kcal:530,p:40,c:55,f:15,veg:2,grain:0,protein:'fish'},
{id:'orzo-ceci',name:'Orzo con ceci, pomodoro e verdure',time:30,diff:1,tags:['legumi','fibra','meal prep'],style:['normal','sport'],ingredients:[['orzo',160,'g'],['ceci cotti',300,'g'],['pomodori',220,'g'],['zucchine',180,'g'],['olio evo',15,'g']],kcal:570,p:25,c:90,f:13,veg:2,grain:1,protein:'legume'},
{id:'polpette-lenticchie',name:'Polpette di lenticchie al pomodoro con cous cous',time:40,diff:3,tags:['vegetariana','comfort','weekend'],style:['elegant','normal'],ingredients:[['lenticchie cotte',320,'g'],['passata di pomodoro',240,'g'],['cous cous',140,'g'],['carote',100,'g'],['olio evo',15,'g']],kcal:550,p:25,c:84,f:14,veg:2,grain:1,protein:'legume'},
{id:'salmone-riso-zucchine',name:'Bowl salmone, riso e zucchine al limone',time:25,diff:2,tags:['omega-3','completa','elegante'],style:['elegant','sport'],ingredients:[['salmone',260,'g'],['riso',150,'g'],['zucchine',250,'g'],['limone',1,'pz'],['olio evo',15,'g']],kcal:610,p:37,c:64,f:22,veg:1,grain:1,protein:'fish'}
];

const INGREDIENT_ALIASES = {
  'zucchina':'zucchine','zucchine':'zucchine','ricotta':'ricotta','cipolla':'cipolla','petto di pollo':'petto di pollo','pollo':'petto di pollo','peperone':'peperoni','peperoni':'peperoni','riso':'riso','lenticchie':'lenticchie cotte','lenticchie cotte':'lenticchie cotte','salmone':'salmone','broccoli':'broccoli','broccolo':'broccoli','patate':'patate','uova':'uova','uovo':'uova','spinaci':'spinaci','ceci':'ceci cotti','ceci cotti':'ceci cotti','pomodoro':'pomodori','pomodori':'pomodori','passata':'passata di pomodoro','passata di pomodoro':'passata di pomodoro','pane':'pane integrale','pane integrale':'pane integrale','tonno':'tonno al naturale','tonno al naturale':'tonno al naturale','tofu':'tofu','carote':'carote','carota':'carote','feta':'feta','mozzarella':'mozzarella','melanzane':'melanzane','funghi':'funghi','piselli':'piselli','orata':'orata','merluzzo':'merluzzo','fesa di tacchino':'fesa di tacchino','tacchino':'fesa di tacchino','yogurt':'yogurt greco','yogurt greco':'yogurt greco','lattuga':'lattuga','cetrioli':'cetrioli','fagiolini':'fagiolini','fagioli':'fagioli cannellini','fagioli cannellini':'fagioli cannellini','cous cous':'cous cous','couscous':'cous cous','orzo':'orzo','pasta':'pasta','pasta integrale':'pasta integrale','gnocchi':'gnocchi','piadina':'piadina integrale','piadina integrale':'piadina integrale','pane pita':'pane pita','olive':'olive','limone':'limone','parmigiano':'parmigiano','olio':'olio evo','olio evo':'olio evo'
};

/* Editorial recipe procedures.
   These are written as kitchen-ready procedures, not generic templates.
   Recipe names are established dishes or standard home-cooking preparations;
   representative recipes were cross-checked against established published recipes. */
const RECIPE_EDITORIAL = {
'pasta-zucchine':{sourceUrl:'https://ricette.giallozafferano.it/Pasta-e-zucchine.html',steps:['Porta a bollore una pentola capiente e sala l’acqua quando bolle. Lava le zucchine, spuntale e tagliale a mezze rondelle sottili; affetta la cipolla.','Scalda l’olio in una padella larga. Aggiungi la cipolla e falla appassire per 3 minuti a fuoco medio; unisci le zucchine e cuoci 7–9 minuti, mescolando, finché diventano tenere e leggermente dorate.','Cuoci la pasta 1 minuto meno del tempo indicato sulla confezione. Conserva circa 120 ml di acqua di cottura prima di scolarla.','Trasferisci la pasta nella padella con le zucchine. Aggiungi la ricotta e poca acqua di cottura alla volta, mescolando energicamente fino a ottenere una crema che rivesta la pasta. Servi subito.']},
'pollo-peperoni':{steps:['Taglia il pollo a bocconcini uniformi e i peperoni a listarelle. Grattugia un po’ di scorza di limone e spremine il succo.','Scalda metà dell’olio in una padella ampia e rosola il pollo 5–7 minuti a fuoco medio-alto, girandolo spesso. Quando è ben dorato e cotto al centro, trasferiscilo su un piatto.','Nella stessa padella aggiungi il resto dell’olio e i peperoni. Cuocili 8–10 minuti, inizialmente a fuoco medio-alto e poi medio, finché sono morbidi ma non sfatti.','Rimetti il pollo, aggiungi scorza e succo di limone e lascia insaporire per 1–2 minuti. Servi con il riso preparato a parte secondo confezione.']},
'lenticchie-pomodoro':{steps:['Trita finemente cipolla e carota. Scalda l’olio in una casseruola e falle appassire 5 minuti a fuoco medio.','Aggiungi la passata e cuoci 5 minuti. Unisci le lenticchie già cotte e circa 100 ml d’acqua; fai sobbollire 8–10 minuti, finché il sugo è denso ma non asciutto.','Nel frattempo tosta il pane in padella o in forno fino a renderlo croccante.','Regola la consistenza delle lenticchie con poca acqua, se necessario. Lascia riposare 2 minuti e servi con il pane.']},
'salmone-broccoli':{steps:['Scalda il forno a 190 °C statico. Pela le patate e tagliale a fette sottili; condiscile con metà dell’olio e disponile in una teglia in uno strato abbastanza uniforme.','Cuoci le patate da sole per 15 minuti. Nel frattempo dividi i broccoli in cimette piccole e asciuga bene il salmone.','Sposta leggermente le patate per fare spazio al salmone, sistema i filetti al centro e distribuisci i broccoli intorno. Completa con l’olio rimasto e inforna per altri 15–18 minuti.','Controlla il punto di cottura nella parte più spessa del salmone: deve essere completamente cotto e sfaldarsi facilmente con una forchetta. Lascia riposare 2 minuti prima di servire.']},
'frittata-spinaci':{steps:['Scalda il forno a 190 °C. Se usi spinaci freschi, falli appassire 2–3 minuti in padella; se sono surgelati, cuocili e strizzali molto bene.','Sbatti le uova in una ciotola senza montarle. Unisci gli spinaci e il parmigiano e mescola fino a distribuire bene il ripieno.','Rivesti o ungi una teglia piccola, versa il composto e livellalo. Cuoci per 12–15 minuti: la superficie deve essere rassodata mentre il centro resta morbido.','Lascia riposare 2 minuti fuori dal forno, poi taglia in spicchi. Tosta il pane e servi insieme.']},
'ceci-couscous':{steps:['Taglia le zucchine a dadini e i pomodori a cubetti. Scalda l’olio in una padella e cuoci le zucchine 6–8 minuti, finché sono dorate.','Aggiungi i ceci scolati e cuoci altri 3–4 minuti per farli insaporire. Spegni il fuoco e incorpora i pomodori.','Prepara il cous cous seguendo il rapporto acqua/cereale indicato sulla confezione. Copri, lascia riposare il tempo previsto e poi sgrana con una forchetta.','Unisci cous cous e condimento, completa con la feta sbriciolata e mescola delicatamente. Servi tiepido.']},
'tonno-fagioli':{steps:['Scola bene tonno e fagioli. Lava i pomodori e tagliali a spicchi o cubetti; affetta sottilmente la cipolla.','Riunisci fagioli, pomodori e cipolla in una ciotola capiente. Condisci con metà dell’olio e mescola senza schiacciare i fagioli.','Sbriciola il tonno sopra l’insalata e aggiungi il resto dell’olio. Mescola solo quanto basta per distribuire il condimento.','Tosta il pane integrale. Lascia riposare l’insalata 5 minuti prima di servire, così i sapori si amalgamano.']},
'pasta-lenticchie':{sourceUrl:'https://ricette.giallozafferano.it/Pasta-e-lenticchie.html',steps:['Trita cipolla e carota. Scalda l’olio in una casseruola e cuoci il trito 4–5 minuti a fuoco medio.','Aggiungi la passata e le lenticchie cotte. Versa acqua calda quanto basta a ottenere un condimento morbido e lascia sobbollire 8 minuti.','Unisci la pasta direttamente nella casseruola. Cuoci aggiungendo altra acqua calda poco alla volta e mescolando spesso, come per una pasta risottata.','Quando la pasta è al dente e il fondo è cremoso, spegni il fuoco e lascia riposare 2 minuti prima di servire.']},
'riso-verdure-tofu':{steps:['Cuoci il riso secondo confezione e lascialo scolare bene. Taglia tofu, broccoli, carote e peperoni in pezzi piccoli e regolari.','Scalda metà dell’olio in una padella ampia. Rosola il tofu 5–6 minuti, girandolo, finché forma una crosticina. Toglilo e tienilo da parte.','Aggiungi il resto dell’olio e cuoci prima carote e broccoli per 4 minuti, poi i peperoni per altri 3–4 minuti.','Rimetti il tofu, aggiungi il riso cotto e salta tutto a fuoco alto per 2–3 minuti, mescolando spesso.']},
'pasta-tonno':{steps:['Porta a bollore l’acqua e cuoci la pasta al dente. Nel frattempo scalda l’olio in una padella.','Aggiungi la passata e cuoci a fuoco medio 8–10 minuti, finché perde parte dell’acqua. Unisci le olive affettate.','Scola il tonno, spezzettalo e aggiungilo al sugo solo negli ultimi 2–3 minuti per evitare che diventi asciutto.','Scola la pasta conservando un po’ d’acqua. Trasferiscila nel sugo e manteca 1 minuto con poca acqua, quindi servi.']},
'pollo-curry-yogurt':{sourceUrl:'https://ricette.giallozafferano.it/Pollo-al-curry.html',steps:['Taglia il pollo a bocconcini. Affetta finemente la cipolla e taglia le carote a piccoli dadini.','Scalda l’olio in una padella. Fai appassire la cipolla 3–4 minuti, aggiungi le carote e cuoci altri 4 minuti. Unisci il pollo e rosolalo su tutti i lati.','Aggiungi il curry e poca acqua calda. Copri a metà e cuoci 10–12 minuti, finché il pollo è completamente cotto e il fondo è ristretto. Unisci gli spinaci negli ultimi 2 minuti.','Spegni il fuoco e incorpora lo yogurt senza farlo bollire, così la salsa resta cremosa. Servi con il riso cotto separatamente.']},
'merluzzo-patate':{steps:['Scalda il forno a 200 °C. Taglia le patate a cubetti piccoli e uniformi, condiscile con metà dell’olio e disponile su una teglia.','Cuoci le patate per 20 minuti, girandole a metà. Taglia i pomodori e prepara il merluzzo asciugando bene i filetti.','Aggiungi merluzzo, pomodori e olive alla teglia. Completa con il resto dell’olio e cuoci altri 10–12 minuti, finché il pesce si sfalda facilmente.','Lascia riposare 2 minuti e servi distribuendo il fondo di cottura sulle patate.']},
'orzo-feta':{steps:['Preriscalda il forno a 200 °C. Taglia zucchine, peperoni e melanzane a cubetti simili e disponili su una teglia con l’olio.','Arrostisci le verdure per 22–25 minuti, mescolandole una volta a metà cottura.','Nel frattempo cuoci l’orzo in acqua bollente secondo confezione, scolalo e fallo sgocciolare bene.','Mescola l’orzo con le verdure ancora tiepide e completa con la feta sbriciolata. Servi caldo o a temperatura ambiente.']},
'shakshuka':{sourceUrl:'https://www.bbcgoodfood.com/recipes/shakshuka',steps:['Affetta finemente cipolla e peperone. Scalda l’olio in una padella larga e cuocili 6–8 minuti a fuoco medio, finché diventano morbidi.','Aggiungi la passata e cuoci scoperto 8–10 minuti, finché il sugo si restringe abbastanza da sostenere le uova.','Con il dorso di un cucchiaio crea quattro cavità nel sugo e sguscia un uovo in ciascuna. Copri e cuoci a fuoco basso 5–7 minuti, finché gli albumi sono rappresi e i tuorli restano morbidi.','Togli dal fuoco, lascia riposare 1 minuto e servi direttamente dalla padella con il pane tostato.']},
'gnocchi-pomodoro':{steps:['Porta a bollore una pentola d’acqua. In una padella prepara la salsa scaldando l’olio e cuocendo la passata 8–10 minuti.','Cuoci gli gnocchi: quando salgono in superficie sono quasi pronti. Scolali con una schiumarola e trasferiscili direttamente nella padella.','Unisci gli spinaci e lascia cuocere 1–2 minuti, finché appassiscono. Mescola delicatamente per non rompere gli gnocchi.','Spegni il fuoco, aggiungi la mozzarella a cubetti, copri 1 minuto e servi quando inizia ad ammorbidirsi.']},
'pasta-broccoli-ricotta':{steps:['Dividi i broccoli in cimette piccole e sbollentali 4–5 minuti nella stessa acqua che userai per la pasta. Scolali tenendo l’acqua.','Porta l’acqua a bollore, cuoci la pasta e nel frattempo salta i broccoli in padella con l’olio per 3 minuti.','Scola la pasta al dente e trasferiscila nella padella. Aggiungi ricotta, parmigiano e 80–100 ml di acqua di cottura.','Mescola a fuoco basso per 1–2 minuti, fino a creare una crema che avvolge pasta e broccoli. Servi immediatamente.']},
'uova-patate-spinaci':{steps:['Taglia le patate a cubetti piccoli. Falle cuocere in padella con metà dell’olio e poca acqua per 12–15 minuti, coperte, finché sono tenere; poi scopri e falle dorare 2 minuti.','A parte fai appassire gli spinaci con il resto dell’olio per 2–3 minuti.','Scalda una padella antiaderente, aggiungi le uova e cuocile al tegamino a fuoco medio-basso finché l’albume è rappreso; non serve girarle.','Servi insieme patate, spinaci e uova, con il pane tostato a lato.']},
'pollo-zucchine':{steps:['Taglia il pollo a striscioline e le zucchine a mezze rondelle. Prepara il cous cous seguendo le istruzioni della confezione.','Scalda l’olio in una padella larga e rosola il pollo 5–6 minuti a fuoco medio-alto, fino a completa cottura. Trasferiscilo in un piatto.','Nella stessa padella cuoci le zucchine 6–8 minuti; devono prendere colore senza diventare molli.','Rimetti il pollo, mescola per 1 minuto e servi sul cous cous sgranato.']},
'salmon-pasta':{steps:['Porta a bollore l’acqua e cuoci la pasta al dente. Nel frattempo taglia il salmone a cubetti e lava gli spinaci.','Scalda l’olio in una padella e cuoci il salmone 4–5 minuti, girando i cubetti, finché sono appena cotti. Aggiungi gli spinaci e falli appassire.','Scola la pasta conservando 100 ml di acqua di cottura. Trasferiscila nella padella con il salmone.','Spegni il fuoco e incorpora lo yogurt con poca acqua di cottura, mescolando fino a ottenere una salsa cremosa. Non far bollire lo yogurt.']},
'insalata-pollo':{steps:['Taglia il pollo a striscioline e cuocilo in una padella calda con metà dell’olio per 6–8 minuti, girandolo, finché è completamente cotto. Lascialo intiepidire.','Lava e asciuga lattuga e pomodori. Taglia le carote a julienne.','Riunisci verdure e ceci scolati. Condisci con l’olio rimasto e mescola.','Aggiungi il pollo tiepido solo alla fine, così la lattuga non perde consistenza. Servi subito.']},
'riso-pollo-verdure':{steps:['Cuoci il riso secondo confezione. Taglia pollo, broccoli, carote e peperoni in piccoli pezzi regolari.','Scalda l’olio in una padella ampia. Rosola il pollo 6–8 minuti fino a completa cottura e spostalo su un piatto.','Cuoci carote e broccoli 4 minuti, poi aggiungi i peperoni e continua per altri 3 minuti.','Rimetti il pollo, incorpora il riso cotto e salta a fuoco alto per 2 minuti, mescolando finché il tutto è caldo e ben distribuito.']},
'pasta-ceci-pomodoro':{steps:['Trita la cipolla. Scalda l’olio in una casseruola e falla appassire per 4 minuti.','Aggiungi passata e ceci scolati e cuoci 8 minuti. Schiaccia con il dorso del cucchiaio una piccola parte dei ceci per rendere il sugo più cremoso.','Cuoci la pasta in acqua bollente finché è al dente; conserva un po’ d’acqua.','Trasferisci la pasta nel sugo, aggiungi poca acqua di cottura e manteca 1–2 minuti.']},
'feta-verdure-pita':{steps:['Taglia pomodori, cetriolo e peperone. Se vuoi una pita più croccante, scaldala in padella 1–2 minuti per lato.','Mescola lo yogurt con un cucchiaio d’acqua per ottenere una salsa morbida.','Apri le pita senza romperle e distribuisci feta, verdure e salsa.','Richiudi e passa la pita ancora 1 minuto in padella, premendola leggermente, oppure servila fresca.']},
'merluzzo-ceci':{steps:['Taglia i pomodori in piccoli pezzi. Scalda l’olio in una padella larga e cuocili 5 minuti.','Aggiungi i ceci e una piccola quantità d’acqua. Fai sobbollire 4 minuti per creare un fondo umido.','Adagia i filetti di merluzzo sui ceci, copri e cuoci 7–10 minuti a fuoco medio-basso, secondo lo spessore dei filetti.','Aggiungi gli spinaci negli ultimi 2 minuti, lasciandoli appassire nel vapore. Servi quando il merluzzo si sfalda facilmente.']},
'pollo-melanzane':{steps:['Taglia la melanzana a cubetti e il pollo a bocconcini. Scalda metà dell’olio in una padella capiente.','Rosola il pollo 5–6 minuti e trasferiscilo in un piatto. Nella stessa padella aggiungi il resto dell’olio e cuoci le melanzane 7–9 minuti, mescolando.','Versa la passata, copri parzialmente e cuoci 8 minuti. Rimetti il pollo e continua per 4–5 minuti.','Nel frattempo cuoci il riso. Servi il pollo e le melanzane con il riso a lato.']},
'pasta-melanzane-mozzarella':{steps:['Taglia le melanzane a cubetti. Scalda l’olio in una padella ampia e cuocile 8–10 minuti, mescolando, fino a quando sono morbide e leggermente dorate.','Aggiungi la passata e lascia restringere il sugo per 8 minuti.','Cuoci la pasta al dente e conserva poca acqua di cottura. Trasferisci la pasta nel sugo e manteca per 1 minuto.','Spegni il fuoco, aggiungi la mozzarella a cubetti e mescola brevemente. Servi quando è appena filante.']},
'frittata-zucchine':{steps:['Taglia le zucchine a rondelle sottili e cuocile con metà dell’olio in una padella per 6–8 minuti, fino a renderle tenere.','Sbatti le uova con la ricotta. Unisci le zucchine ormai tiepide e mescola.','Scalda una padella antiaderente con il resto dell’olio, versa il composto e cuoci a fuoco basso 4–5 minuti con coperchio.','Quando la superficie è quasi rappresa, gira la frittata con un piatto oppure termina la cottura sotto grill. Servi con lattuga e pane tostato.']},
'riso-lenticchie':{steps:['Cuoci il riso secondo confezione. Nel frattempo taglia carote e broccoli in piccoli pezzi.','Scalda l’olio in padella e cuoci carote e broccoli 7–9 minuti; devono restare leggermente croccanti.','Aggiungi le lenticchie cotte e cuoci 3 minuti, giusto il tempo di scaldarle.','Incorpora il riso e salta tutto per 2 minuti. Servi caldo, senza schiacciare le lenticchie.']},
'tacchino-patate':{steps:['Scalda il forno a 200 °C. Taglia le patate e le carote in pezzi piccoli e simili. Condiscili con metà dell’olio e inforna per 20 minuti.','Taglia la fesa di tacchino a bocconcini. Scalda una padella con il resto dell’olio e rosola la carne 5–6 minuti.','Trasferisci il tacchino nella teglia con patate e carote e continua la cottura 8–10 minuti, finché la carne è completamente cotta.','Lascia riposare 2 minuti prima di servire, distribuendo i succhi della teglia sulle verdure.']},
'orata-patate':{steps:['Scalda il forno a 200 °C. Taglia le patate a fettine sottili e condiscile con metà dell’olio. Cuocile in teglia 20 minuti.','Adagia l’orata o i filetti sulle patate e distribuisci i pomodori intorno. Completa con l’olio rimasto.','Continua la cottura per 12–15 minuti, regolando il tempo in base allo spessore del pesce. La polpa deve staccarsi facilmente.','Lascia riposare 2 minuti e servi con le patate e il fondo di cottura.']},
'risotto-funghi':{sourceUrl:'https://blog.giallozafferano.it/asilannablu/risotto-con-champignon-e-parmigiano/',steps:['Pulisci i funghi con un panno o una spazzolina e affettali. Scalda una casseruola larga e cuocili 5–6 minuti con parte dell’olio; mettili da parte.','Nella stessa casseruola fai appassire la cipolla tritata con il resto dell’olio per 3–4 minuti. Aggiungi il riso e tostalo 2 minuti, mescolando.','Versa acqua o brodo caldo poco alla volta, aggiungendo altro liquido quando il precedente è quasi assorbito. Mescola regolarmente e cuoci circa 16–18 minuti.','A metà cottura incorpora i funghi. A fuoco spento aggiungi il parmigiano e mescola energicamente; lascia riposare 1 minuto prima di servire.']},
'pasta-piselli':{steps:['Porta a bollore l’acqua e cuoci la pasta. Nel frattempo cuoci i piselli in padella con metà dell’olio per 6–7 minuti.','Schiaccia grossolanamente circa un terzo dei piselli con una forchetta e mescolali alla ricotta per creare una crema rustica.','Scola la pasta conservando un po’ d’acqua. Uniscila alla padella con i piselli e aggiungi la crema di ricotta.','Completa con poca acqua di cottura e succo di limone, mescolando finché il condimento aderisce alla pasta.']},
'ceci-spinaci-pane':{steps:['Scalda l’olio in una casseruola. Aggiungi la passata e cuoci 5 minuti.','Unisci i ceci scolati e circa 100 ml d’acqua. Schiaccia qualche cece contro il fondo della pentola e cuoci 8 minuti a fuoco basso.','Aggiungi gli spinaci in due volte, mescolando finché appassiscono. Continua la cottura per 2 minuti.','Tosta il pane fino a renderlo croccante e servi i ceci cremosi sopra o accanto al pane.']},
'tuna-pasta-lemon':{steps:['Cuoci la pasta al dente. Taglia i pomodori a cubetti e sgocciola il tonno.','In una ciotola grande mescola pomodori, tonno, olio e scorza di limone. Lascia riposare mentre la pasta cuoce.','Scola la pasta e passala rapidamente sotto acqua fredda se la vuoi fredda; lasciala sgocciolare bene.','Unisci la pasta al condimento, aggiungi succo di limone poco alla volta e mescola. Servi a temperatura ambiente o fredda.']},
'pollo-yogurt-cetriolo':{steps:['Taglia il pollo a bocconcini e cuocilo in padella con un filo d’olio per 6–8 minuti, finché è completamente cotto. Lascialo intiepidire.','Mescola lo yogurt con il cetriolo tagliato molto fine. Se il cetriolo è molto acquoso, strizzalo leggermente prima di unirlo.','Scalda la piadina 30–60 secondi per lato. Distribuisci lattuga, pomodori, pollo e salsa allo yogurt.','Arrotola la piadina piegando prima i lati verso l’interno e poi chiudendo dal basso. Servi subito.']},
' tofu-curry':{steps:['Taglia tofu, broccoli e carote a pezzi regolari. Scalda l’olio in una padella ampia e rosola il tofu 5–6 minuti, finché è dorato.','Aggiungi carote e broccoli e cuoci 7–8 minuti con poca acqua, finché sono teneri ma ancora consistenti.','Unisci il curry e un paio di cucchiai d’acqua. Mescola per 1 minuto per tostare le spezie senza bruciarle.','Spegni il fuoco e aggiungi lo yogurt. Mescola fino a ottenere una salsa morbida e servi con il riso cotto a parte.']},
'uova-piselli':{steps:['Scalda l’olio in una padella e cuoci i piselli 6–7 minuti con un piccolo splash d’acqua, finché sono teneri.','Sbatti le uova in una ciotola. Aggiungi i piselli e metà dei pomodori tagliati a cubetti.','Versa il composto nella padella, abbassa il fuoco e mescola lentamente con una spatola per ottenere uova morbide e non asciutte.','Tosta il pane e servi con il resto dei pomodori freschi.']},
'insalata-salmone':{steps:['Cuoci le patate a cubetti in acqua bollente per 10–12 minuti, finché sono tenere ma non si sfaldano. Scolale e lasciale intiepidire.','Cuoci i fagiolini in acqua bollente per 5–7 minuti; scolali e passali sotto acqua fredda per fermare la cottura.','Cuoci il salmone in padella o al forno fino a completa cottura, poi lascialo riposare 2 minuti e sfaldalo in pezzi grandi.','Riunisci patate, fagiolini e pomodori, condisci con l’olio e incorpora delicatamente il salmone.']},
'pasta-tacchino-spinaci':{steps:['Cuoci la pasta al dente. Nel frattempo taglia il tacchino a striscioline.','Scalda l’olio in padella e rosola il tacchino 5–7 minuti. Aggiungi la passata e cuoci altri 5 minuti.','Unisci gli spinaci e cuoci 2 minuti, finché appassiscono.','Scola la pasta conservando poca acqua, trasferiscila nel condimento e manteca 1–2 minuti con un goccio d’acqua.']},
'couscous-pollo':{steps:['Prepara il cous cous secondo confezione e sgranalo con una forchetta. Taglia pollo, zucchine e peperoni in pezzi piccoli.','Scalda l’olio in una padella larga e cuoci il pollo 6–8 minuti, finché è completamente cotto. Spostalo su un piatto.','Nella stessa padella cuoci prima i peperoni 4 minuti, poi le zucchine altri 4–5 minuti. Unisci i pomodori negli ultimi 2 minuti.','Rimetti il pollo, spegni il fuoco e mescola con il cous cous. Lascia riposare 2 minuti prima di servire.']},
'melanzane-ceci':{steps:['Scalda il forno a 200 °C. Dividi le melanzane a metà nel senso della lunghezza e incidi la polpa a griglia, senza bucare la buccia.','Spennella con metà dell’olio e cuoci con il lato tagliato verso l’alto per 20–25 minuti, finché la polpa è morbida.','Scava delicatamente parte della polpa, tritala e mescolala con ceci e passata. Riporta il ripieno nelle barchette.','Completa con la mozzarella e inforna altri 8–10 minuti, finché il formaggio è sciolto e leggermente dorato.']},
'patate-tonno':{steps:['Cuoci le patate intere o a metà in acqua bollente per circa 15 minuti, finché una forchetta entra facilmente. Scolale e lasciale intiepidire.','Mescola yogurt e tonno sgocciolato fino a ottenere una crema rustica.','Schiaccia grossolanamente le patate con una forchetta, evitando di ridurle in purea, e condiscile con metà dell’olio.','Servi le patate con la crema di tonno, lattuga e pomodori conditi con l’olio restante.']},
'orzo-ceci':{steps:['Cuoci l’orzo in acqua bollente secondo confezione e scolalo quando è ancora leggermente al dente.','In padella scalda l’olio, cuoci le zucchine a cubetti 6–8 minuti e aggiungi i pomodori per altri 2 minuti.','Unisci i ceci scolati e scalda 3 minuti.','Aggiungi l’orzo, mescola a fuoco basso per 2 minuti e servi caldo, lasciandolo riposare un minuto prima di impiattare.']},
'polpette-lenticchie':{sourceUrl:'https://ricette.giallozafferano.it/Polpette-di-lenticchie.html',steps:['Se le patate non sono già cotte, lessale finché sono morbide; scolale e falle intiepidire.','Schiaccia le patate e le lenticchie in una ciotola. Forma un impasto compatto lavorandolo con una forchetta; se necessario lascialo riposare 10 minuti per farlo rassodare.','Forma polpette piccole e regolari. Disponile su una teglia unta o rivestita e cuocile a 200 °C per 20–25 minuti, girandole una volta a metà.','Nel frattempo scalda la passata in padella. Servi le polpette con il cous cous preparato a parte e il sugo sopra o a lato.']},
'salmone-riso-zucchine':{steps:['Cuoci il riso secondo confezione. Taglia le zucchine a mezze rondelle.','Scalda metà dell’olio in una padella e cuoci le zucchine 7–8 minuti. Trasferiscile in un piatto.','Nella stessa padella cuoci il salmone a cubetti 4–5 minuti, girandolo con delicatezza. Deve essere appena cotto al centro.','Rimetti le zucchine, aggiungi scorza e succo di limone e mescola per 30 secondi. Servi con il riso.']}
};

/* Fix one accidental whitespace key and attach editorial metadata. */
RECIPE_EDITORIAL['tofu-curry']=RECIPE_EDITORIAL[' tofu-curry'];
delete RECIPE_EDITORIAL[' tofo-curry'];
for(const r of RECIPES){const d=RECIPE_EDITORIAL[r.id];if(d){r.steps=d.steps;r.sourceUrl=d.sourceUrl||null;r.verified=true;r.editorialStatus='curated';}}
